version : '3'

services:
  database:
    build: ./database
  apparel:
    build: ./apparel
    volumes:
      - ./apparel:/app
    depends_on:
      - database
    ports:
      - 5001:80
  prices:
    build: ./prices
    volumes:
      - ./prices:/app
    depends_on:
      - apparel
    ports:
      - 5002:80