version : '3'

services:
  database:
    build: ./database
    networks: 
      - core
  apparel:
    build: ./apparel
    networks:
      - core
    volumes:
      - ./apparel:/app
    depends_on:
      - database
    ports:
      - 5001:80
  prices:
    build: ./prices
    networks:
      - core
      - site
    volumes:
      - ./prices:/app
    depends_on:
      - apparel
    ports:
      - 5002:80
  site:
    build: ./site
    networks: 
      - site
    volumes:
      - ./site:/src
    depends_on:
      - prices
    ports:
      - 5000:80

networks:
  core:
    driver: bridge 
  site:
    driver: bridge